project:
  type: website
  output-dir: docs
  resources:
    - cv_pdf

website:
  title: "Alexandre MATHIEU"
  navbar:
    logo: images/logo_source.jpeg
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: conference.qmd
        text: Conference
      - href: editing_referee.qmd
        text: Edition & Referee
      - href: Teaching.qmd
        text: Teaching
      - href: journalism.qmd
        text: Science Popularization

format:
  html:
    theme: flatly
    toc: true
    css: styles.css



